package com.rms.db.mapper;

import com.rms.db.model.ElementGuid;
import java.util.List;

public interface ElementGuidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_guid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_guid
     *
     * @mbg.generated
     */
    int insert(ElementGuid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_guid
     *
     * @mbg.generated
     */
    ElementGuid selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_guid
     *
     * @mbg.generated
     */
    List<ElementGuid> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_guid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ElementGuid record);
}