package com.rms.db.mapper;

import com.rms.db.model.Element;
import java.util.List;

public interface ElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element
     *
     * @mbg.generated
     */
    int insert(Element record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element
     *
     * @mbg.generated
     */
    Element selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element
     *
     * @mbg.generated
     */
    List<Element> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Element record);
}