package com.rms.db.mapper;

import com.rms.db.model.JiraIssue;
import java.util.List;

public interface JiraIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_issue
     *
     * @mbg.generated
     */
    int insert(JiraIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_issue
     *
     * @mbg.generated
     */
    JiraIssue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_issue
     *
     * @mbg.generated
     */
    List<JiraIssue> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JiraIssue record);
}