package com.rms.db.model;

import java.util.Date;

public class ElementGuid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column element_guid.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column element_guid.element_id
     *
     * @mbg.generated
     */
    private Long elementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column element_guid.guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column element_guid.file_id
     *
     * @mbg.generated
     */
    private Long fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column element_guid.is_deleted
     *
     * @mbg.generated
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column element_guid.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column element_guid.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column element_guid.id
     *
     * @return the value of element_guid.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column element_guid.id
     *
     * @param id the value for element_guid.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column element_guid.element_id
     *
     * @return the value of element_guid.element_id
     *
     * @mbg.generated
     */
    public Long getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column element_guid.element_id
     *
     * @param elementId the value for element_guid.element_id
     *
     * @mbg.generated
     */
    public void setElementId(Long elementId) {
        this.elementId = elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column element_guid.guid
     *
     * @return the value of element_guid.guid
     *
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column element_guid.guid
     *
     * @param guid the value for element_guid.guid
     *
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column element_guid.file_id
     *
     * @return the value of element_guid.file_id
     *
     * @mbg.generated
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column element_guid.file_id
     *
     * @param fileId the value for element_guid.file_id
     *
     * @mbg.generated
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column element_guid.is_deleted
     *
     * @return the value of element_guid.is_deleted
     *
     * @mbg.generated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column element_guid.is_deleted
     *
     * @param isDeleted the value for element_guid.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column element_guid.create_time
     *
     * @return the value of element_guid.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column element_guid.create_time
     *
     * @param createTime the value for element_guid.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column element_guid.update_time
     *
     * @return the value of element_guid.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column element_guid.update_time
     *
     * @param updateTime the value for element_guid.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}